[package]
name = "elrond-infrastructure"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
elrond-application = { path = "../application" }
elrond-domain = { path = "../domain" }
sqlx.workspace = true
