[package]
name = "elrond-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
elrond-application = { path = "../application" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
