[package]
name = "elrond-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Elrond composition root and application binary."

[[bin]]
name = "elrond"
path = "src/main.rs"

[dependencies]
elrond-api.workspace = true
elrond-application.workspace = true
elrond-infrastructure.workspace = true

anyhow.workspace = true
axum.workspace = true
dotenvy.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
